### ISSUE TITLE
NSX Manager NTP

### ISSUE THREAD

**Issue by hakkurt** [lamw/vghetto-vsphere-automated-lab-deployment#11]
I suggest to add ntp as an NSX OVF deployment parameter
 
$ovfconfig.common.vsm_ntp_0.value

**Comment by lamw** [comment]
Great suggestion, I must have missed that when I had probed the OVA. Just added, please see https://github.com/lamw/vghetto-vsphere-automated-lab-deployment/blob/master/vsphere-6.5-vghetto-standard-lab-deployment.ps1#L629
