### ISSUE TITLE
NSX Manager DNS settings

### ISSUE THREAD

**Issue by hakkurt** [lamw/vghetto-vsphere-automated-lab-deployment#12]
Hi William,
During my tests, I realized that NSX manager DNS fields shown as empty. Is it same for you ?

**Comment by lamw** [comment]
Which DNS fields are you referring to?

**Comment by hakkurt** [comment]
Normally we're sending DNS via $ovfconfig.common.vsm_dns1_0.value = $dns as an ovf parameter. But after OVF deployment is completed, NSX Manager DNS fields shown as empty. See screenshot
![dns](https://user-images.githubusercontent.com/23055580/32387529-ce6f1622-c0d5-11e7-82a7-535e4f784583.PNG) 

in screenshot, I added DNS entry manually

**Comment by lamw** [comment]
Also, which script are you using?

**Comment by hakkurt** [comment]
$ovfconfig = Get-OvfConfiguration $global:NSXOVA
        $ovfconfig.NetworkMapping.VSMgmt.value = $global:VMNetwork
        $ovfconfig.common.vsm_hostname.value = $global:NSXHostname
        $ovfconfig.common.vsm_ip_0.value = $global:NSXIPAddress
        $ovfconfig.common.vsm_netmask_0.value = $global:NSXNetmask
        $ovfconfig.common.vsm_gateway_0.value = $global:NSXGateway
		$ovfconfig.common.vsm_dns1_0.value = $global:dns
		$ovfconfig.common.vsm_ntp_0.value = $global:ntp
        $ovfconfig.common.vsm_domain_0.value = $global:domainname
        $ovfconfig.common.vsm_isSSHEnabled.value = $true
        $ovfconfig.common.vsm_isCEIPEnabled.value = $false
        $ovfconfig.common.vsm_cli_passwd_0.value = $global:NSXUIPassword
        $ovfconfig.common.vsm_cli_en_passwd_0.value = $global:NSXCLIPassword
		$cluster = Get-Cluster -Name $global:VMCluster			
		$vmhost = Get-VMHost -Location $cluster | Where { $_.ConnectionState -eq "Connected" } | Get-Random # Select a connected host
		
		$datastore = Get-Datastore -Name $global:VMDatastore
			
		My-Logger "Deploying NSX VM $global:NSXDisplayName ..."
        $vm = Import-VApp -Source $global:NSXOVA -OvfConfiguration $ovfconfig -Name $global:NSXDisplayName -Location $cluster -VMHost $vmhost -Datastore $datastore -DiskStorageFormat thin

		# Temporary for test environment - remove for Production
		Set-VM -VM $vm -NumCpu $global:NSXvCPU -MemoryGB $global:NSXvMEM -Confirm:$false
		
        My-Logger "Powering On $global:NSXDisplayName ..."
        $vm | Start-Vm -RunAsync | Out-Null

**Comment by lamw** [comment]
I just looked at my code and it looks fine. I even went through a deployment and DNS *is* being set correctly. This is NSX 6.3, haven't tried with later OVAs but assuming the variables haven't changed, it should work

**Comment by hakkurt** [comment]
I tested with 6.3.4 version. Anyway, I saw similar behaviour even manuel deployments.
