### ISSUE TITLE
Error at importing ESXi OVA

### ISSUE THREAD

**Issue by wojciehm** [lamw/vghetto-vsphere-automated-lab-deployment#15]
At line 479 of the script it is failing.

`$vm = Import-VApp -Server $viConnection -Source $NestedESXiApplianceOVA -Name $VMName -VMHost $vmhost -Datastore $datastore -DiskStorageFormat thin`

Solutiuon is provided https://readysetvirtual.wordpress.com/2018/04/09/powercli-import-vapp-ova-hostname-cannot-be-parsed/ but should be fixed.

[10-10-2018_03:02:19] Connecting to 192.168.255.50 ...
[10-10-2018_03:02:20] Deploying Nested ESXi VM lab02-esxi01 ...
Import-VApp : 10.10.2018 15:02:22       Import-VApp             Invalid URI: The hostname could not be parsed.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:479 char:19
+ ...       $vm = Import-VApp -Server $viConnection -Source $NestedESXiAppl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-VApp], ViError
    + FullyQualifiedErrorId : Client20_NfcLease_RunNfcTask_Error,VMware.VimAutomation.ViCore.Cmdlets.Commands.ImportVA
   pp

[10-10-2018_03:02:22] Updating VM Network ...
Get-NetworkAdapter : 10.10.2018 15:02:22        Get-NetworkAdapter              NetworkAdapter with name 'Network adapter 1' was not found
 using the specified filter(s).
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:482 char:19
+ ...            $vm | Get-NetworkAdapter -Name "Network adapter 1" | Set-N ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-NetworkAdapter], VimException
    + FullyQualifiedErrorId : Core_OutputHelper_WriteNotFoundError,VMware.VimAutomation.ViCore.Cmdlets.Commands.Virtua
   lDevice.GetNetworkAdapter

Get-NetworkAdapter : 10.10.2018 15:02:27        Get-NetworkAdapter              NetworkAdapter with name 'Network adapter 2' was not found using the specified filter(s).
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:486 char:23
+ ...            $vm | Get-NetworkAdapter -Name "Network adapter 2" | Set-N ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-NetworkAdapter], VimException
    + FullyQualifiedErrorId : Core_OutputHelper_WriteNotFoundError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetNetworkAdapter

[10-10-2018_03:02:27] Updating vCPU Count to 4 & vMEM to 20 GB ...
Set-VM : 10.10.2018 15:02:27    Set-VM          Value cannot be found for the mandatory parameter VM
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:492 char:13
+             Set-VM -Server $viConnection -VM $vm -NumCpu $NestedESXiv ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-VM], VimException
    + FullyQualifiedErrorId : Core_BaseCmdlet_UnknownError,VMware.VimAutomation.ViCore.Cmdlets.Commands.SetVM

[10-10-2018_03:02:27] Updating vSAN Caching VMDK size to 20 GB ...
Get-HardDisk : Cannot validate argument on parameter 'VM'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:495 char:52
+             Get-HardDisk -Server $viConnection -VM $vm -Name "Hard di ...
+                                                    ~~~
    + CategoryInfo          : InvalidData: (:) [Get-HardDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetHardDisk

[10-10-2018_03:02:27] Updating vSAN Capacity VMDK size to 100 GB ...
Get-HardDisk : Cannot validate argument on parameter 'VM'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:498 char:52
+             Get-HardDisk -Server $viConnection -VM $vm -Name "Hard di ...
+                                                    ~~~
    + CategoryInfo          : InvalidData: (:) [Get-HardDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetHardDisk

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:541 char:13
+             $orignalExtraConfig+=$b
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:542 char:13
+             $orignalExtraConfig+=$c
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:543 char:13
+             $orignalExtraConfig+=$d
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:544 char:13
+             $orignalExtraConfig+=$e
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:545 char:13
+             $orignalExtraConfig+=$f
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:546 char:13
+             $orignalExtraConfig+=$g
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:547 char:13
+             $orignalExtraConfig+=$h
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:548 char:13
+             $orignalExtraConfig+=$i
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:549 char:13
+             $orignalExtraConfig+=$j
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:550 char:13
+             $orignalExtraConfig+=$k
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:551 char:13
+             $orignalExtraConfig+=$l
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:552 char:13
+             $orignalExtraConfig+=$m
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

[10-10-2018_03:02:27] Adding guestinfo customization properties to lab02-esxi01 ...
You cannot call a method on a null-valued expression.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:558 char:13
+             $task = $vm.ExtensionData.ReconfigVM_Task($spec)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Task : 10.10.2018 15:02:27  Get-Task                The identifier Task- resulted in no objects.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:559 char:22
+             $task1 = Get-Task -Id ("Task-$($task.value)")
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-Task], VimException
    + FullyQualifiedErrorId : Client20_OutputTracker_ReportNotFoundLocators_LocatorNotProduced,VMware.VimAutomation.ViCore.Cmdlets.Commands.GetTask

[10-10-2018_03:02:27] Powering On lab02-esxi01 ...
Start-VM : Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:563 char:48
+             Start-VM -Server $viConnection -VM $vm -Confirm:$false |  ...
+                                                ~~~
    + CategoryInfo          : InvalidData: (:) [Start-VM], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,VMware.VimAutomation.ViCore.Cmdlets.Commands.StartVM

[10-10-2018_03:02:27] Deploying Nested ESXi VM lab02-esxi02 ...
Import-VApp : 10.10.2018 15:02:29       Import-VApp             Invalid URI: The hostname could not be parsed.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:479 char:19
+ ...       $vm = Import-VApp -Server $viConnection -Source $NestedESXiAppl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-VApp], ViError
    + FullyQualifiedErrorId : Client20_NfcLease_RunNfcTask_Error,VMware.VimAutomation.ViCore.Cmdlets.Commands.ImportVApp

[10-10-2018_03:02:29] Updating VM Network ...
Get-NetworkAdapter : 10.10.2018 15:02:29        Get-NetworkAdapter              NetworkAdapter with name 'Network adapter 1' was not found using the specified filter(s).
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:482 char:19
+ ...            $vm | Get-NetworkAdapter -Name "Network adapter 1" | Set-N ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-NetworkAdapter], VimException
    + FullyQualifiedErrorId : Core_OutputHelper_WriteNotFoundError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetNetworkAdapter

Get-NetworkAdapter : 10.10.2018 15:02:34        Get-NetworkAdapter              NetworkAdapter with name 'Network adapter 2' was not found using the specified filter(s).
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:486 char:23
+ ...            $vm | Get-NetworkAdapter -Name "Network adapter 2" | Set-N ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-NetworkAdapter], VimException
    + FullyQualifiedErrorId : Core_OutputHelper_WriteNotFoundError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetNetworkAdapter

[10-10-2018_03:02:34] Updating vCPU Count to 4 & vMEM to 20 GB ...
Set-VM : 10.10.2018 15:02:34    Set-VM          Value cannot be found for the mandatory parameter VM
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:492 char:13
+             Set-VM -Server $viConnection -VM $vm -NumCpu $NestedESXiv ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-VM], VimException
    + FullyQualifiedErrorId : Core_BaseCmdlet_UnknownError,VMware.VimAutomation.ViCore.Cmdlets.Commands.SetVM

[10-10-2018_03:02:34] Updating vSAN Caching VMDK size to 20 GB ...
Get-HardDisk : Cannot validate argument on parameter 'VM'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:495 char:52
+             Get-HardDisk -Server $viConnection -VM $vm -Name "Hard di ...
+                                                    ~~~
    + CategoryInfo          : InvalidData: (:) [Get-HardDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetHardDisk

[10-10-2018_03:02:34] Updating vSAN Capacity VMDK size to 100 GB ...
Get-HardDisk : Cannot validate argument on parameter 'VM'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:498 char:52
+             Get-HardDisk -Server $viConnection -VM $vm -Name "Hard di ...
+                                                    ~~~
    + CategoryInfo          : InvalidData: (:) [Get-HardDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetHardDisk

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:541 char:13
+             $orignalExtraConfig+=$b
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:542 char:13
+             $orignalExtraConfig+=$c
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:543 char:13
+             $orignalExtraConfig+=$d
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:544 char:13
+             $orignalExtraConfig+=$e
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:545 char:13
+             $orignalExtraConfig+=$f
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:546 char:13
+             $orignalExtraConfig+=$g
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:547 char:13
+             $orignalExtraConfig+=$h
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:548 char:13
+             $orignalExtraConfig+=$i
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:549 char:13
+             $orignalExtraConfig+=$j
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:550 char:13
+             $orignalExtraConfig+=$k
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:551 char:13
+             $orignalExtraConfig+=$l
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:552 char:13
+             $orignalExtraConfig+=$m
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

[10-10-2018_03:02:34] Adding guestinfo customization properties to lab02-esxi02 ...
You cannot call a method on a null-valued expression.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:558 char:13
+             $task = $vm.ExtensionData.ReconfigVM_Task($spec)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Task : 10.10.2018 15:02:34  Get-Task                The identifier Task- resulted in no objects.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:559 char:22
+             $task1 = Get-Task -Id ("Task-$($task.value)")
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-Task], VimException
    + FullyQualifiedErrorId : Client20_OutputTracker_ReportNotFoundLocators_LocatorNotProduced,VMware.VimAutomation.ViCore.Cmdlets.Commands.GetTask

[10-10-2018_03:02:34] Powering On lab02-esxi02 ...
Start-VM : Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:563 char:48
+             Start-VM -Server $viConnection -VM $vm -Confirm:$false |  ...
+                                                ~~~
    + CategoryInfo          : InvalidData: (:) [Start-VM], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,VMware.VimAutomation.ViCore.Cmdlets.Commands.StartVM

[10-10-2018_03:02:34] Deploying Nested ESXi VM lab02-esxi03 ...
Import-VApp : 10.10.2018 15:02:36       Import-VApp             Invalid URI: The hostname could not be parsed.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:479 char:19
+ ...       $vm = Import-VApp -Server $viConnection -Source $NestedESXiAppl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-VApp], ViError
    + FullyQualifiedErrorId : Client20_NfcLease_RunNfcTask_Error,VMware.VimAutomation.ViCore.Cmdlets.Commands.ImportVApp

[10-10-2018_03:02:36] Updating VM Network ...
Get-NetworkAdapter : 10.10.2018 15:02:36        Get-NetworkAdapter              NetworkAdapter with name 'Network adapter 1' was not found using the specified filter(s).
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:482 char:19
+ ...            $vm | Get-NetworkAdapter -Name "Network adapter 1" | Set-N ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-NetworkAdapter], VimException
    + FullyQualifiedErrorId : Core_OutputHelper_WriteNotFoundError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetNetworkAdapter

Get-NetworkAdapter : 10.10.2018 15:02:41        Get-NetworkAdapter              NetworkAdapter with name 'Network adapter 2' was not found using the specified filter(s).
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:486 char:23
+ ...            $vm | Get-NetworkAdapter -Name "Network adapter 2" | Set-N ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-NetworkAdapter], VimException
    + FullyQualifiedErrorId : Core_OutputHelper_WriteNotFoundError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetNetworkAdapter

[10-10-2018_03:02:41] Updating vCPU Count to 4 & vMEM to 20 GB ...
Set-VM : 10.10.2018 15:02:41    Set-VM          Value cannot be found for the mandatory parameter VM
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:492 char:13
+             Set-VM -Server $viConnection -VM $vm -NumCpu $NestedESXiv ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-VM], VimException
    + FullyQualifiedErrorId : Core_BaseCmdlet_UnknownError,VMware.VimAutomation.ViCore.Cmdlets.Commands.SetVM

[10-10-2018_03:02:41] Updating vSAN Caching VMDK size to 20 GB ...
Get-HardDisk : Cannot validate argument on parameter 'VM'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:495 char:52
+             Get-HardDisk -Server $viConnection -VM $vm -Name "Hard di ...
+                                                    ~~~
    + CategoryInfo          : InvalidData: (:) [Get-HardDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetHardDisk

[10-10-2018_03:02:41] Updating vSAN Capacity VMDK size to 100 GB ...
Get-HardDisk : Cannot validate argument on parameter 'VM'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:498 char:52
+             Get-HardDisk -Server $viConnection -VM $vm -Name "Hard di ...
+                                                    ~~~
    + CategoryInfo          : InvalidData: (:) [Get-HardDisk], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,VMware.VimAutomation.ViCore.Cmdlets.Commands.VirtualDevice.GetHardDisk

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:541 char:13
+             $orignalExtraConfig+=$b
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:542 char:13
+             $orignalExtraConfig+=$c
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:543 char:13
+             $orignalExtraConfig+=$d
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:544 char:13
+             $orignalExtraConfig+=$e
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:545 char:13
+             $orignalExtraConfig+=$f
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:546 char:13
+             $orignalExtraConfig+=$g
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:547 char:13
+             $orignalExtraConfig+=$h
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:548 char:13
+             $orignalExtraConfig+=$i
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:549 char:13
+             $orignalExtraConfig+=$j
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:550 char:13
+             $orignalExtraConfig+=$k
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:551 char:13
+             $orignalExtraConfig+=$l
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Method invocation failed because [VMware.Vim.OptionValue] does not contain a method named 'op_Addition'.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:552 char:13
+             $orignalExtraConfig+=$m
+             ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (op_Addition:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

[10-10-2018_03:02:41] Adding guestinfo customization properties to lab02-esxi03 ...
You cannot call a method on a null-valued expression.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:558 char:13
+             $task = $vm.ExtensionData.ReconfigVM_Task($spec)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Get-Task : 10.10.2018 15:02:41  Get-Task                The identifier Task- resulted in no objects.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:559 char:22
+             $task1 = Get-Task -Id ("Task-$($task.value)")
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-Task], VimException
    + FullyQualifiedErrorId : Client20_OutputTracker_ReportNotFoundLocators_LocatorNotProduced,VMware.VimAutomation.ViCore.Cmdlets.Commands.GetTask

[10-10-2018_03:02:41] Powering On lab02-esxi03 ...
Start-VM : Cannot validate argument on parameter 'VM'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At D:\Download\HomeLab\6.7\Homelab6.7-failure.ps1:563 char:48
+             Start-VM -Server $viConnection -VM $vm -Confirm:$false |  ...
+                                                ~~~
    + CategoryInfo          : InvalidData: (:) [Start-VM], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,VMware.VimAutomation.ViCore.Cmdlets.Commands.StartVM

PS D:\Download\HomeLab\6.7>

**Comment by adamrushuk** [comment]
Thanks for logging this @wojciehm, expanding the OVA and pointing the the OVF file enabled importing the ESXi VM.

**Comment by bml104** [comment]
@adamrushuk can you please explain what "expanding the OVA and pointing the the OVF file enabled importing the ESXi VM." means? Rename the ova to ovf?

**Comment by adamrushuk** [comment]
sure @bml104 , by expanding I meant unzip the OVA; it's a compressed file with multiple files inside, including an OVF file.
