### ISSUE TITLE
The '<' operator is reserved for future use

### ISSUE THREAD

**Issue by dwaynejhall** [lamw/vghetto-vsphere-automated-lab-deployment#17]
William

I am attempting to use your script - I am running Powershell 5.1 build 14409 1012 with Powercli 6.5 R1 build 4624819 - I followed the directions to update the variables to match what I want to deploy and when I run the PS1 file via Powercli or Powershell ISE I get several lines of code where it has an issue with the open < as well it wants to bracket & with " "

Have you seen this before and am I missing something - to be honest I have only used very simple JSON templates in Azure training which were already prebuilt and this script of yours is very comprehensive.  Any help would be appreciated!

Thanks
Dwayne

At E:\Downloads\Software\VMware\Lab\vsphere-6.5-vghetto-standard-lab-deployment-HDJLAB.ps1:136 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At E:\Downloads\Software\VMware\Lab\vsphere-6.5-vghetto-standard-lab-deployment-HDJLAB.ps1:140 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At E:\Downloads\Software\VMware\Lab\vsphere-6.5-vghetto-standard-lab-deployment-HDJLAB.ps1:145 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At E:\Downloads\Software\VMware\Lab\vsphere-6.5-vghetto-standard-lab-deployment-HDJLAB.ps1:150 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At E:\Downloads\Software\VMware\Lab\vsphere-6.5-vghetto-standard-lab-deployment-HDJLAB.ps1:154 char:19
+ </a>              </li>
+                   ~
The '<' operator is reserved for future use.
At E:\Downloads\Software\VMware\Lab\vsphere-6.5-vghetto-standard-lab-deployment-HDJLAB.ps1:390 char:185
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At E:\Downloads\Software\VMware\Lab\vsphere-6.5-vghetto-standard-lab-deployment-HDJLAB.ps1:394 char:18
+ </form>          <h3 class="pt-2">Join GitHub today</h3>
+                  ~
The '<' operator is reserved for future use.
At E:\Downloads\Software\VMware\Lab\vsphere-6.5-vghetto-standard-lab-deployment-HDJLAB.ps1:497 char:214
+ ... it/13f8253a9707a1aa4f4938f9f4e57a16e377a0c1">Fixing "sort" -&gt; Sort ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
At E:\Downloads\Software\VMware\Lab\vsphere-6.5-vghetto-standard-lab-deployment-HDJLAB.ps1:503 char:54
+   <summary class="btn-link" aria-haspopup="dialog"  >
+                                                      ~
Missing file specification after redirection operator.
At E:\Downloads\Software\VMware\Lab\vsphere-6.5-vghetto-standard-lab-deployment-HDJLAB.ps1:520 char:17
+ </a>            </li>
+                 ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : RedirectionNotSupported

**Comment by lamw** [comment]
How did you download the script, it looks like you may had a bad download or something got miss-converted since this looks more like syntax errors. 

Unfortunately, I can't see most of what you pasted use triple (`) between your output so it'll properly display it in Github

**Comment by dwaynejhall** [comment]
Hey William

Thanks for the quick response - I use Chrome and I right clicked it and downloaded it - however when I select the link it brings me to the code and it appears to be a script I can now recognize

I figured it is something I did wrong - first time use Github - I will grab the code and save it 

Thanks
I will tell you how the deployment goes
Dwayne
