### ISSUE TITLE
Failed to download file from guest with error '(vim.fault.InvalidGuestLogin)

### ISSUE THREAD

**Issue by dwaynejhall** [lamw/vghetto-vsphere-automated-lab-deployment#18]
William

After I got a proper copy of your script I entered in all the variables and ran the script - it deployed the 3 ESXi hosts and the VCSA - but during the attempt to configure the VCSA the script had repeatedly tried to login to my existing vcenter appliance to download /var/log/firstboot/rpmInstall.json

Here are the log files and the generated json files (renamed to allow upload to github) that were located in the Appdata install folder vcsaCliInstaller-2018-10-12-19-36-kpmblg

So basically I have 3 ESXi nested hosts all configured with IPs and names but the VCSA didn't get configured image attached

As a test I made sure that I was able to putty into my existing VCSA with the creds i used in the script, I also have all the records in DNS, and I was able to find the json file on my VCSA appliance and I enabled the Bash Shell during the running of the script

I tried this twice (deleted the vAPP first time) but haven't rebooted my VCSA yet

Do you have any ideas?  First off is this the correct process and if so have any suggestions?

Thanks
Dwayne
 
![vcsalab01-error](https://user-images.githubusercontent.com/44074860/46896346-91928300-ce4a-11e8-889a-d6b946c01e93.png)

[vcsa-cli-installer.log](https://github.com/lamw/vghetto-vsphere-automated-lab-deployment/files/2474714/vcsa-cli-installer.log)

[ovftool.log](https://github.com/lamw/vghetto-vsphere-automated-lab-deployment/files/2474716/ovftool.log)

[vcsa-cli-installer.json.log](https://github.com/lamw/vghetto-vsphere-automated-lab-deployment/files/2474720/vcsa-cli-installer.json.log)

[generated_install.json.log](https://github.com/lamw/vghetto-vsphere-automated-lab-deployment/files/2474721/generated_install.json.log)

**Comment by lamw** [comment]
From the logs, it looks like it wasn't able to connect to the VCSA using the Guest Operations API to retrieve status and eventually it gives up (which you can see in the vcsa-cli-installer.log file) and hence the failure. The issue is happening outside of the deployment script. Can ask that you try to deploy just the VCSA using the UI or CLI installer to see if you're having success using the inputs you've provided to my script? This should at least verify that you're able to deploy it which my script simply calls the CLI Installer

**Comment by dwaynejhall** [comment]
William

I have the same problem when I attempt to deploy the VMware-VCSA-all-6.5.0-4602587 appliance to either venter or ESXi and I found this KB about the root password having expired - https://kb.vmware.com/s/article/51124

I only grabbed the GA version of the ISO from a link in one of your articles - can I use any version of 6.5 in this script?

Thanks
Dwayne

**Comment by dwaynejhall** [comment]
William

I decided to grab the last version of 6.5 (before you couldn't upgrade to the 6.7) VMware-VCSA-all-6.5.0-8024368 and I was able to properly deploy it to my environment.  However when I run your script the vcsa-cli-installer.log file still shows that something is trying to connect to my existing vCenter Appliance and download rpmInstall.json file - I made sure that the creds (both root and administrator@vsphere.local had the same password).  **Is it normal for this json file to be downloaded from the existing VCSA?**  Also I had rebooted my vCenter Appliance yesterday.  I will attach the logs once it is done (timesout) but I think it looks the same as before

2018-10-16 18:24:55,398 - vCSACliInstallLogger - TRACE - Cannot download file /var/log/firstboot/rpmInstall.json from vcsa01.hdjlab.int. Got error: Failed to download file from guest with error '(vim.fault.GuestOperationsUnavailable) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The guest operations agent could not be contacted.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []

**Comment by dwaynejhall** [comment]
I think I spoke too soon it looks like it has progressed past the download attempts into the service installs and the starting - looks like it is working.  I appreciate the time you have taken to build all this up - will save time for me and likely a lot of others for testing.  I will close this issue once I have confirmed everything

**Comment by dwaynejhall** [comment]
Hi William

Looks like it all deployed properly only one error related to vSAN and when I check the Events it shows one error event for each host "Could not scan vesxi6-#" - I will investigate - now I can play around with vSAN - thanks again - your scripts rock!

[10-16-2018_03:30:58] Enabling VSAN Space Efficiency/De-Dupe & disabling VSAN He
alth Check ...
Set-VsanClusterConfiguration : 10/16/2018 3:31:46 PM
Set-VsanClusterConfiguration            General vSAN error.
Reason 1:
At E:\Downloads\Software\VMware\lab\vsphere-6.5-vghetto-standard-lab-deployment
-HDJLAB.ps1:857 char:83
+ ... usterName | Set-VsanClusterConfiguration -SpaceEfficiencyEnabled $tru ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-VsanClusterConfigurat
   ion], ViError
    + FullyQualifiedErrorId : Storage_Impl_VsanServiceImpl_ErrorSettingSpaceEf
   ficiency,VMware.VimAutomation.Storage.Commands.Cmdlets.Vsan.SetVsanCluster
  Configuration
