### ISSUE TITLE
Feature Suggestion: Open log file in separate window while deployment runs

### ISSUE THREAD

**Issue by h0bbel** [lamw/vghetto-vsphere-automated-lab-deployment#2]
How about adding something like this to the script:

`start-process powershell.exe -argument '-nologo -noprofile -executionpolicy bypass -command Get-Content .\vsphere65-vghetto-lab-deployment.log -Tail 2 -Wait'`

This opens a new powershell window and runs Get-Content to display the log file as the script runs.

This is useful as it contains more progress information than the output of the script itself:

![screenshot 2016-11-23 11 48 01](https://cloud.githubusercontent.com/assets/4984953/20558937/b5c4e714-b172-11e6-9c03-0173a5c21054.png)

**Comment by lamw** [comment]
Incorporated into the latest version of the script that will support vSphere 6.7
